# Generated by Django 3.1 on 2020-08-09 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='event_address',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='event_category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_date',
            new_name='event_final_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='event_initial_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='event_place',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='virtual',
            new_name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 15, 15, 52, 925975, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='thumbnail_image'),
            preserve_default=False,
        ),
    ]
