# Generated by Django 3.1 on 2020-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200809_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('CONFERENCE', 'Conferencia'), ('SEMINAR', 'Seminario'), ('CONGRESS', 'Congreso'), ('COURSE', 'Curso')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], max_length=10),
        ),
    ]
