# Generated by Django 3.1 on 2020-08-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200809_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default='default-thumbnail.jpg', upload_to='thumbnail_image'),
        ),
    ]
