# Generated by Django 3.1 on 2020-08-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200812_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default='default-thumbnail.jpg', upload_to='thumbnail_image'),
        ),
    ]
